project_id = "ovqulpgcdddtadobwlan"

[functions.ai-split-task]
verify_jwt = false

[functions.ai-archive-process]
verify_jwt = false

[functions.ai-archive-expand]
verify_jwt = false

[functions.ai-archive-multi]
verify_jwt = false

[functions.ai-archive-clean]
verify_jwt = false
