import { X, Printer } from "lucide-react";
import { HEALTH_METRICS } from "@/lib/health-data";

interface Props {
  open: boolean;
  onClose: () => void;
}

/**
 * Lab-friendly test names you can hand to a phlebotomist / clinic.
 * These are the standard order names. Independent of how we label them in the UI.
 */
const LAB_TESTS: { panel: string; tests: { name: string; note?: string }[] }[] = [
  {
    panel: "Lipid Panel",
    tests: [
      { name: "Total Cholesterol" },
      { name: "LDL Cholesterol (calculated or direct)" },
      { name: "HDL Cholesterol" },
      { name: "Triglycerides" },
    ],
  },
  {
    panel: "Glucose / Diabetes",
    tests: [
      { name: "Fasting Plasma Glucose", note: "fasting ≥8h" },
      { name: "Hemoglobin A1c (HbA1c)" },
    ],
  },
  {
    panel: "Complete Blood Count (CBC)",
    tests: [{ name: "Hemoglobin (Hb)" }],
  },
  {
    panel: "Kidney Function",
    tests: [
      { name: "Serum Creatinine" },
      { name: "Estimated Glomerular Filtration Rate (eGFR)" },
    ],
  },
  {
    panel: "In-clinic measurements",
    tests: [
      { name: "Blood Pressure (systolic / diastolic, mmHg)" },
      { name: "Resting Heart Rate (bpm)" },
    ],
  },
];

export default function LabTestListModal({ open, onClose }: Props) {
  if (!open) return null;

  const handlePrint = () => {
    const html = `<!doctype html><html><head><meta charset="utf-8"><title>Lab tests. MindsetForest Health</title>
<style>
  body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;color:#111;padding:32px;max-width:680px;margin:0 auto;line-height:1.45}
  h1{font-size:22px;margin:0 0 4px}
  p.sub{color:#555;margin:0 0 20px;font-size:13px}
  h2{font-size:14px;text-transform:uppercase;letter-spacing:.05em;color:#333;margin:18px 0 6px;border-bottom:1px solid #ddd;padding-bottom:4px}
  ul{margin:0;padding-left:20px}
  li{margin:3px 0;font-size:14px}
  .note{color:#777;font-size:12px;margin-left:6px}
  footer{margin-top:24px;font-size:11px;color:#888;border-top:1px solid #ddd;padding-top:10px}
</style></head><body>
<h1>Lab tests to request</h1>
<p class="sub">Hand this list to your clinic. These are the standard order names.</p>
${LAB_TESTS.map(p => `<h2>${p.panel}</h2><ul>${p.tests.map(t => `<li>${t.name}${t.note ? `<span class="note">(${t.note})</span>` : ""}</li>`).join("")}</ul>`).join("")}
<footer>Generated by MindsetForest Health · For personal tracking, not medical advice.</footer>
<script>window.onload=()=>{window.print();}</script>
</body></html>`;
    const w = window.open("", "_blank", "width=720,height=900");
    if (!w) return;
    w.document.write(html);
    w.document.close();
  };

  const allText = LAB_TESTS.map(
    p => `${p.panel}\n${p.tests.map(t => `  • ${t.name}${t.note ? ` (${t.note})` : ""}`).join("\n")}`,
  ).join("\n\n");

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(allText);
    } catch {
      /* noop */
    }
  };

  return (
    <div
      className="fixed inset-0 z-[200] bg-black/60 backdrop-blur-sm flex items-center justify-center p-4"
      onClick={onClose}
    >
      <div
        className="glass-card max-w-md w-full max-h-[85vh] overflow-y-auto p-5"
        onClick={e => e.stopPropagation()}
      >
        <div className="flex items-start justify-between mb-3">
          <div>
            <div className="text-base font-bold text-foreground">Lab tests to request</div>
            <p className="text-xs text-muted-foreground mt-0.5">
              Standard order names you can show at the clinic.
            </p>
          </div>
          <button
            onClick={onClose}
            className="p-1 text-muted-foreground hover:text-foreground"
            aria-label="Close"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="space-y-3">
          {LAB_TESTS.map(panel => (
            <div key={panel.panel}>
              <div className="text-[11px] font-bold uppercase tracking-wider text-muted-foreground mb-1">
                {panel.panel}
              </div>
              <ul className="space-y-1">
                {panel.tests.map(t => (
                  <li key={t.name} className="text-sm text-foreground/90 flex gap-2">
                    <span className="text-primary mt-1">•</span>
                    <span>
                      {t.name}
                      {t.note && <span className="text-muted-foreground"> ({t.note})</span>}
                    </span>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        <div className="flex items-center gap-2 mt-5 pt-3 border-t border-border">
          <button
            onClick={handlePrint}
            className="flex-1 px-3 py-2 rounded-xl gradient-purple text-primary-foreground font-bold text-xs inline-flex items-center justify-center gap-1.5 hover:opacity-90"
          >
            <Printer className="w-3.5 h-3.5" /> Print
          </button>
          <button
            onClick={handleCopy}
            className="px-3 py-2 rounded-xl bg-muted/40 text-muted-foreground hover:text-foreground border border-border text-xs font-semibold"
          >
            Copy as text
          </button>
        </div>
        <p className="text-[10px] text-muted-foreground italic mt-2 text-center">
          For personal tracking. Total checks tracked: {HEALTH_METRICS.length}.
        </p>
      </div>
    </div>
  );
}